### ISSUE TITLE
Version in comment does not match actual version

### ISSUE THREAD

**Issue by dregad** [tomi-vanek/wsdl-viewer#2]
https://github.com/tomi-vanek/wsdl-viewer/blob/acbb08c94fbec1a791b03f30c3b2801621445924/wsdl-viewer.xsl#L24-L27

https://github.com/tomi-vanek/wsdl-viewer/blob/acbb08c94fbec1a791b03f30c3b2801621445924/wsdl-viewer.xsl#L166

**Comment by tomi-vanek** [comment]
Version number was elevated to 3.1.04 and fixed in the code.

**Comment by tomi-vanek** [comment]
fixed.
