### ISSUE TITLE
Invalid reference to `wsdl-viewer.js` script

### ISSUE THREAD

**Issue by dregad** [tomi-vanek/wsdl-viewer#3]
Hello

Many years ago we had a discussion about this [[1]], and I ended up updating the xsl locally to remove the script.

Today I noticed that it is still present

https://github.com/tomi-vanek/wsdl-viewer/blob/acbb08c94fbec1a791b03f30c3b2801621445924/wsdl-viewer.xsl#L2256-L2261

Maybe you want to remove it ?

[1]: https://mantisbt.org/bugs/view.php?id=18049#c48765

**Comment by dregad** [comment]
I can submit a pull request if you like

**Comment by tomi-vanek** [comment]
Thank you, going to fix this problem.
Of course a PR would speed up the fix ;-)
tomi

**Comment by dregad** [comment]
Here you go 😃

**Comment by tomi-vanek** [comment]
Thanks, merged. In next commit I am going to fix also the modular version in src with your change..
